title: sofa-pbrpc
description: My Personal Blog
author: sofa-pbrpc
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/zd-double/sofa-pbrpc
about: A light-weight RPC implement of google protobuf RPC framework.
disqus_shortname: sofa-pbrpc 
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Benchmark
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/zd-double/sofa-pbrpc
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

#url: "http://aboutashu.com/hcz-jekyll-blog"
#baseurl: "/sofa-pbrpc-blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
