title: sofa-pbrpc
description: Sofa-pbrpc Blog
author: sofa-pbrpc 
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png 
github: https://github.com/zd-double/sofa-pbrpc
about: A light-weight RPC implement of google protobuf RPC framework.
disqus_shortname: zddouble
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Benchmark
      url: /benchmark/
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/zd-double/sofa-pbrpc
      icon: fa-github
    - text: Documents
      url: /documents/
      icon: fa-feed
      
social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "https://zd-double.github.io"
#baseurl: "/"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
